import MainNavbar from "@components/shared/MainNavbar";
import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainFooter from "@components/shared/MainFooter";
import { cn } from "@lib/utils";
import { ThemeProvider } from "@components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Authentication App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={cn(inter.className, "flex flex-col min-h-screen")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MainNavbar />
          <main className="flex-1">{children}</main>
          <MainFooter />
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
